kind: Deployment
apiVersion: apps/v1
metadata:
  name: sx2-fs
  labels:
    app: sx2-fs

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sx2-fs
  template:
    metadata:
      labels:
        app: sx2-fs
    spec:
      containers:
        - name: sx2-fs
          image: stacksparrow4/priv:sx2-fs
          ports:
            - name: web
              containerPort: 80
          envFrom:
          - secretRef:
              name: fs-password
---
apiVersion: v1
kind: Service
metadata:
  name: sx2-fs

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: sx2-fs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sx2-fs
spec:
  rules:
  - host: fs.stacksparrow4.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sx2-fs
            port:
              name: web